// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wifbrfckzpkwpuualtmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpZmJyZmNrenBrd3B1dWFsdG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDU4NjMsImV4cCI6MjA3MzQ4MTg2M30.XkapFzwXRfmjBAVpvgiIPyT6vTrPt6b79K2F9ij68qA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});